spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tektok
    username: user
    password: example
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
